### ISSUE TITLE
bug with input adornment

### ISSUE THREAD

**Issue by HoangNguyen-CA** [HoangNguyen-CA/restaurant-website#6]
Input component throws error on line 64: 

Warning: Failed prop type: The prop `children` is marked as required in `ForwardRef(InputAdornment)`, but its value is `null`.

**Comment by OE10x2** [comment]
https://github.com/HoangNguyen-CA/restaurant-website/commit/10d40da08c6b849d04bfcf2e4720be93f85bb457
It was a one-liner fix after all
